apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cluster-issuer
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-cluster-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-cluster-issuer